---
title: "Nested Data"
author: "Sheyanne Rodriguez"
date: "2024-09-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Main data structures in Python -

1.  Lists

2.  Tuples

3.  Dictionaries

4.  Sets

You can nest these data structures one inside the other. For example:

1.  List of lists

2.  List of tuples

3.  List of dictionaries

4.  Dictionary of lists

5.  Dictionary of dictionaries

6.  Dictionary of lists of dictionaries ... etc

You MUST know how to handle a complex nested data to get the info you want.

The methodology is to go step by step with how the complex nested data is structured.

At each level of nesting, you must understand how to correctly address/ access the elements at that level.

What we will do here is work through a methodology for determining and addressing nested structures.

Some examples:

### Dictionary of dictionaries

```{python}
nested_data = { 
  "first_name": "John",
  "last_name": "Smith",

"address": { "street_address": "21 2nd Street",
"city": "New York",
"state": "NY",
"postal_code": "10021-3100"}
}
#there are three keys : first name last name & address
#the other dictionary is the { stree_address....} which is within the dictionary
```

### The "address" part of the code is the nested dict within the overall dict.

Now let's look at how to address this with code. At each step below, we will go back to Python Tutor and cross reference the data structures visual representation with the syntax of how we are addressing each element.

```{python}
type(nested_data)
```

```{python}
#note that the dictionary contains three key-value pairs
#the last key's value is a dict with 4 key-value pairs
for key, value in nested_data.items(): #looping over the outter dictionary or first dictionary
  print("Key : {} , \n Value : {}\n".format(key,value))
```

```{python}
len(nested_data)
```

Addressing the highest level key in the overall dictionary

```{python}
#What are the data types of the values
print(type(nested_data['first_name']))
print(type(nested_data['last_name']))
print(type(nested_data['address']))
```

Now let's see how to address the dictionary that is the value of the address key.

```{python}
for key, value in nested_data['address'].items():
  print("Key : {} | Value : {}\n".format(key,value))
  #print(f"Key : {key} | Value : {value}\n")
```

How do we address the nested dictionary, within the address dictionary?

(how we can simply access elements without iterating over the whole thing. So, let's say in the original data structure, all we care about is getting the value associated with the street address key.)

*How can we go about getting that out of our nested data?*

-   we can access 21 2nd street directly and here's how we do that:

**Note that we simply add the next level of data onto our data reference.**

We say:

-   look within nested_data

-   grab the value associated with the address key: 'street_address'

-   we input the value associated within our nested_data

```{python}
nested_data['address']['street_address']
```

SO, at each level of nesting, what you do is add an additional set of brackets on and access your element directly using the key name associated with that element.

Below are some examples:

```{python}
print(nested_data['address']['city'])
print(nested_data['address']['state'])
print(nested_data['address']['postal_code'])
```

Common nested data structures:

1.  Dictionary of dictionaries

2.  Dictionary of lists

3.  List of lists

4.  List of dictionaries

5.  List of tuples

### Dictionary of lists

```{python}
dict_of_lists = {"names":["Rich", "Chris", "Katie"], "cities":["Atlanta", "Los Angeles", ["Chattanooga", "Nashville"]]}
```

So, do we address the nested list elements?

```{python}
#Address the appropriate dictionary key,
# Then the appropriate list location
dict_of_lists["names"][0]
```

Notice in the value of the *cities* key, the 3rd element in the list is another list – **a nested list** within the list.

If we wanted to return the string *Nashville,* How would we do that?

1.  It is in the "cities" key.

2.  The list is the 3rd element within the list that is the dictionary value.

3.  The string *Nashville* is the 2nd element in the list.

```{python}
dict_of_lists["cities"][2][1] #3 levels deep
#[2][1]
```

### **Lists of Lists**

```{python}
list_of_lists = [
  ["Rich", "Chris", "Katie"],
  ["Atlanta", "Los Angeles", ["Chattanooga", "Nashville"]]
]
```

Let's take this out to Python Tutor.

So, how do we address the nested list elements?

```{python}
#access the idividual lists within the parent list
#display(list_of_lists[0])
print(list_of_lists[1][1])
```

```{python}
#access an element within one of the child lists
print(list_of_lists[1][1])
```

```{python}
#access an element in the lowest level list
print(list_of_lists[1][2])
print(list_of_lists[1][2][1]) #Three sets of brackets for 3 lists
```

### List of Dictionaries

```{python}
list_of_dicts = [{"names":"Rich",
"cities":"Atlanta"},
{"names":"Chris",
"cities":"Los Angeles"},
{"names":"Katie",
"cities":["Chattanooga", "Nashville"]}]
list_of_dicts
```

So, how do we address the nested list elements?

```{python}
list_of_dicts[0]
```

```{python}
list_of_dicts[2]
```

```{python}
print(list_of_dicts[2]['cities'])
print(list_of_dicts[2]['cities'][1])
```

```{python}
list_of_dicts
```

```{python}
#Hypothetical Exam Question:

#Given a list of dictionaries, return two sets: set of unique cities and set of unique namesz;

cities_set = set()
names_set = set()

for d in list_of_dicts: #iterating over elements
  #print(d)
  names_set.add(d['names'])
  #print(d['cities'])
  if type(d['cities']) is str:
    cities_set.add(d['cities'])
  else:
    for city in d['cities']:
      #print(city)
      cities_set.add(city)
      
print(cities_set)
print()
print(names_set)
```

**List of tuples**

```{python}
list_of_tuples = [
  ("Rich", "Atlanta"),
  ("Chris", "Los Angeles"),
  ("Katie", ["Chattanooga", "Nashville"])
]
```

So, how do we address the nested list elements?

```{python}
list_of_tuples[0]
```

```{python}
print(list_of_tuples[2][0])
print(list_of_tuples[2][1][1]) #3 layers deep
```

```{python}
#Hypothetical Exam Question -- Example 2:

#Given a list of dictionaries, return two sets: set of unique cities and set of unique namesz;

cities_set = set()
names_set = set()

for t in list_of_tuples: 
  #print(t)
  names_set.add(t[0])
  
  
  #names_set.add(d['names'])
  #print(d['cities'])
  if type(t[1]) is str:
    cities_set.add(t[1]) #if it is type str then i want to add that directly to cities_set
  else:
    for city in t[1]:
      #print(city)
      cities_set.add(city)
      
print(cities_set)
print()
print(names_set)
```
