---
title: 'Python Bootcamp: Dictionaries'
author: "Sheyanne Rodriguez"
date: "2024-09-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples:

The following code will create two empty dictionaries, and then populate them with values.

```{python}
#Constructing a new dictionary
dict1 = {} #Curly brackets method
dict2 = dict() #dict() method

#Populate the dictionary, assign a key and a value
dict1["key1"] = "value1"
dict2["key2"] = "value2"

print(f"Dictionary 1: {dict1}")
print(f'"Dictionary 2: {dict2}"') #f'..' displays quotations
```

What if we already have a collection of keys and values? We can use any of the following methods to create the dictionary:

```{python}
#Keyword argument list // dict() function
dict1 = dict(key1 = "value1", key2 = "value2")

#Dictionary literal=={}
dict2 = {"key3":"value3", "key4":"value4"}

#List of tuples
dict3 = dict([
  ("key5", "value5"), #first value of the tuple is key & second is the value
  ("key6", "value6") #therefore ("key", "value")
])

#Display the dictionary
print(f"Dictionary 1: {dict1}")
print(f"Dictionary 2: {dict2}")
print(f"Dictionary 3: {dict3}")

```

## Indexing

We can think of the act of "looking up" a value for a given key as a type of **indexing**. Actually, we've already seen indexing when we looked at lists and tuples! Let's recap how that works:

-   Lists and tuples facilitate **indexing** by *ordering* their values.

-   We can use the order of the sequence to index by using integers.

    -   The index is the *position* of the value in the sequence. For example:

```{python}
#Say we have a list of four food items
food_items = ["apple", "chicken", "eggs", "bread"]

#What is the value in position 2? (remember, we start at 0)
food_items[2] #This returns the value in the list at this position
```

Python's syntax for indexing values from a list/tuple and a dictionary are identical!! However, instead of using a *position* (remember, dictionaries have no *order*), we use the **key** to index the **value.**

```{python}

#Maybe we want to keep track of how many containers we have of each food

food_items = {"apple" : 2,
"chicken" : 1,
"eggs" : 4,
"bread" : 2
}
print(food_items)

#How many containers of eggs do we have:
food_items["eggs"] # This returns the value at this key
```

What happens if we try to index on a key which isn't in the dictionary?

```{python}
# How much candy do we have 
try: 
  food_items["candy"]
except KeyError:
  print("Uh oh! This will give you an error!")
```

We can see that this causes Python to raise a KeyError! One way to avoid this problem is to use the .get() method. This allows you to specify a default value if the key is not present in the dictionary. You could also use a Default Dictionary.

```{python}
#Let's use .get() instead
food_items.get("candy", 0)
#if candy already exists in the dictionary, it will give that value
#if it does not exist, it will create the key and assign the value of 0 == 
#("", 0) replace 0 with 1 and will output a value of 1

```

## Iteration

We can treat Python Dictionaries as *iterables.* This means we can loop over them like we can with lists or tuples.

-   You **should not rely on the elements being presented in a certain order.**

-   Iterating over a dictionary will iterate over the **keys,** not the **values!**

```{python}
#Create a Harry Potter dictionary
harry_potter_dict = {"Harry Potter": "Gryffindor",
"Ron Weasley": "Gryffindor",
"Hermione Granger": "Gryffindor",
"Draco Malfoy": "Slytherin"}

#Let's see which house each character belongs to
for character in harry_potter_dict:
  #We can use the key to get the value when we iterate!
  house = harry_potter_dict[character]
  #Print the result
  print(f"{character} belongs to {house} house.")
```

## Dictionary size and checking for membership

-   We can use len() to determine how many keys are in our dictionary.

-   We can use the *key in d* expression to determine whether a key is in a dictionary.

```{python}
#How many characters are in our dictionary
print(len(harry_potter_dict))

#Is Harry Potter one of the keys
print("Harry Potter" in harry_potter_dict)

if "Harry Potter" in harry_potter_dict:
  print('yes')
```

## Adding Elements

We can dramatically add elements to a Python dict.

-   Method 1: "Assign" a value to a non-existent key.

-   Method 2: Use *.update()* to add many keys and values at the same time.

    -   We can store new key-value pairs in a dict or an iterable

-   Method 3: Use *.setdefault()* to add a key and value, but *only if the key does not already exist.*

**IMPORTANT**: Methods 1 & 2 will **remap** the existing values for the given keys! If this is not what you want to have happen, you should implement a check where you see whether a key is already in the dictionary before assigning a value (or use Method 3).

```{python}
#This is a helper function for printing our dictionaries
from pprint import pprint

#Create a Harry Potter dictionary
harry_potter_dict = {"Harry Potter": "Gryffindor",
"Harmione Grainger": "Gryffindor"}

#Custom printer (ignore)
def pretty_print(text):
  print(text)
  pprint(harry_potter_dict)
  
#display the dictionary
pretty_print("Starting Dictionary: ")
```

### Method 1

```{python}
#Method 1
harry_potter_dict["Ron Weasly"] = "Gryffindor"

#Display the dictionary
pretty_print("After Method 1:")
```

### Method 2

```{python}
#Method 2
#Use a dictionary to update a dictionary
add_character_1 = {"Albus Dumbledore": "Headmaster",
"luna Lovegood": "Ravenclaw"}

#Use iterables to update a dictionary
add_character_2 = [["Draco Malfoy", "Slytherin"],
["Cedric Diggory", "Hufflepuff"]]

#Merge dictionaries
harry_potter_dict.update(add_character_1)
harry_potter_dict.update(add_character_2)

#Display the dictionary
pretty_print("After Method 2:")
```

### Method 3

```{python}
#Method 3
#Adding a new character, but only if the key doesn't already exist
harry_potter_dict.setdefault("Rubeus Hagrid", "Gryffindor")

#Let's try to add a character to the wrong house
harry_potter_dict.setdefault("Harry Potter", "Slytherin")

#Display the dictionary (Notice Harry Potter's house hasn't changed)
pretty_print("After Method 3:")
```

## Removing Elements

-   Method 1: Use del keyword.

    -   WARNING: This will cause Python to raise an error if they key does NOT exist in your dict already!

-   Method 2: Use .pop()

    -   If you specify a default value, this will not raise an error if they key does NOT exist.

```{python}
#Method 1
if 'Ron Weasly' in harry_potter_dict:
  del harry_potter_dict["Ron Weasly"]
  
  #Display the dictionary
pretty_print("After Method 1:")
```

```{python}
#Method 2
harry_potter_dict.pop("Draco Malfoy", None)

#This key isnt in the dictionary, so if we dont specify a "Default" value 
#(Specified as None here) Python will raise an error
harry_potter_dict.pop("Bilbo Baggins", None)

#Display
pretty_print("After Method 2:")
```

## Mutating

Remember, dictionary keys must be *unique.* If we assign a new value to an existing key, the dictionary will remap the relationship!

```{python}
#Remapping with assignment
harry_potter_dict["Harry Potter"] = "GRADUTATED"

#Remapping with .update()
harry_potter_dict.update({"Harmione Grainger" : "GRADUATED",
"Albus Dumbledore": "INSTRUCTOR",
"Rubeus Hagrid": "INSTRUCTOR"})

#Display
pretty_print("Harry Potter has now graduated!")
```

If the value associated with a key is mutable, we can change the value and the dictionary value will reflect those changes. Here's an example:

```{python}
#Create a list, which is mutable
fruits = ["apple", "pear", "blueberry"]

#Create a dict where the value is the list
food_type = {"fruits": fruits}

#Add a new value to the LIST
fruits.append("kiwi")
#Do the same thing by indexing into the dictionary
food_type["fruits"].append("bananas")

#What does the dictionary contain now
print(food_type)
```

## .keys() .values() and .items()

Each of these methods will let you access the contents of the dictionary as a *sequence.*

-   .keys() fetches the keys

-   .values() fetches the values

-   .items() will return 2-element tuples containing the key and the value.

```{python}
print(harry_potter_dict.keys())
```

```{python}
print(harry_potter_dict.values())
```

```{python}
print(harry_potter_dict.items())

print()
for k, v in harry_potter_dict.items():
  print(k)
  print(v)
  print('\n')
```

## Summary

-   Dictionaries let you map keys to values.

    -   You van use them to group similar collections of data and associate the data with meaningful IDs, such as names.

-   Dictionaries are mutable.

    -   You can easily add, change, and remove their contents.

-   These are often several ways to perform the same task with dictionaries.

    -   Check the documentation if you're not sure how to do a specific operation.
