---
title: "Control Flow"
author: "Sheyanne Rodriguez"
date: "2024-08-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Control Flow

The term *control flow* (or control structures, as opposed to data structures) refers to code constructs—like "if" statements, "for" loops, and "function calls" —that cause statements to execute in a nonlinear order.

Key concepts:

-   Functions

-   Conditionals )if-elif-else; inline if-else)

-   For-loops and iterators

-   while-loops and other loop constructs (break, continue)

## Aside: Assertions

Example: if you were writing a program to compute n! (the factorial of n), perhaps you want to restrict the input value of n that you wish to consider to be non-negative. A useful code construct in that case is an *assert* statement, which has the form:

assert boolean_condition, error_string

which does nothing if boolean_condition is True or, if it is False, aborts the execution and prints the message error_string.

```{python}
n = 0 #Change 0 to -3 to see the error
assert n >= 0, f"'n' must be non-negative but instead has the value {n}." 
```

## Functions

**Defining functions.** Consider this example and note the following:

-   def statement, which names the function, declares its arguments, and ends in a :

-   An optional document string, which can be retrieved by "help" queries

-   Indentation: In Python, indentation is significant and strictly exforced. Blocks of code must be indented consistently

-   The *return* statement, which specifies the value that the function returns to the caller

```{python}
def evens(a, b):
  #Returns a list of even integers in '[a, b)',
  #given integers 'a' and 'b'.
  
  assert isinstance(a, int) and isinstance(b, int), f"One of 'a:{type(a)}' or 'b:{type(b)}' is not an integer."
  return [x for x in range(a, b) if (x % 2) == 0]
evens(-7, 10)
```

```{python}
def foo():
  return 'a', 1.23, 'b'
foo()
```

**None returns.** A function that lacks a return statement still produces a value, namely, None (of type NoneType).

```{python}
def no_op():
  pass
print(no_op(), type(no_op()))
```

**Functions are objects.**

```{python}
print(evens, type(evens))
```

```{python}
def run_two_param_function(fun, x, y):
  assert callable(fun), \
  f"First arg is not callable; it's a {type(fun)})."
  return fun(x, y)

print(run_two_param_function(evens, 3, 12))
print(run_two_param_function(divmod, 13, 3)) #divmod is a built-in function
```

**Anonymous, or lambda, functions.** Occasionally, you need to define a short, single-use function that returns a value. In such cases, the *lambda* construct gives you a succinct way to do so.

In this first example, the *lambda* defines a two-parameter function that, given arguments name x and y return 2x-y.

```{python}
def somefunction(x, y):
  return 2*x - y

run_two_param_function(lambda x, y: 2*x -y, 7, 3)
```

Here is another example: First consider Python's built-in sorted function, which returns a sorted instance of an input collection.

```{python}
sorted([8, 3, 2, -7, 10, 11, 4, 1, -4])
```

However, suppose the list has more complex values, like:

```{python}
data = [{'first':'Guido', 'last':'Van Rossum', 'YOB':1956},
{'first':'Grace', 'last':'Hopper', 'YOB':1906},
{'first':'Alan', 'last':'Turing', 'YOB':1912}]
```

Suppose we wish to sort this list by year-of-birth. The *sorted* function takes an optional parameter that allows us to define the sort key. The key is given by a function that, given a list element, returns the value to use for sorting:

```{python}
sorted(data, key=lambda x: x['YOB'])
```

Conceptually, the following are equivalent:

```{python}
def get_year_of_birth_v1(x):
  return x['YOB']

get_year_of_birth_v2 = lambda x: x['YOB']

print(get_year_of_birth_v1(data[0]),
get_year_of_birth_v2(data[0]))
```

| Under the hood, these are not equivalent. In particular, the lambda function has no name. When debugging and tracing through a program, it may be harder to know wherer you are.

```{python}
def a_girl_has_a_name():
  return None
print(a_girl_has_a_name.__name__, ':', type(a_girl_has_a_name))

a_girl_has_no_name = lambda: None

print(a_girl_has_no_name.__name__, ':', type(a_girl_has_no_name))
```

**Default arguments.** The sorted example was a function that took an *optional* parameter, which allowed you to customize the key. Your functions can have a similar feature if you supply *default* arguments.

```{python}
#(base*factor + offset)**power

def mul_add_pow(base, factor = 1, offset = 0, power = 1):
  """`mul_add_pow(b, f, o, p)`: returns `(b*f + o)**p`."""
  return (base*factor +offset)**power
print(mul_add_pow(5))               #(5*1 + 0)**1
print(mul_add_pow(5, 2, 3))         #(5*2 + 3)**1
print(mul_add_pow(5, 2, power = 2)) #(5*2 + 0)**2
print(mul_add_pow(5, 2, 4, -1))     #(5*2+ 4)*(-1) ~ 0.07
print(mul_add_pow(5, power = -1, factor = 2, offset = 4)) #sa,e as above; named args in any order

```

| Order of arguments: Optional arguments must appear *after* required arguments. At the call-site, unnamed optional arguemtns are assigned in the order of the definition; names arguments must appear after unnamed arguments, but may appear in any order.

**Flexible arguments.** Per the note above, you can think of the arguments to a function as being two groups: *required arguments,* which do not have names, and *optional arguments,* which are named. Indeed, you can write functions where you do not know these in advance but leave placeholders for them:

```{python}
#def func(*req, **opt):
#   ...
```

These are available in the body of the function as a tuple (req) and dictionary (opt), as the next example illustrates.

```{python}
def catch_all(*req, **opt):
  print("req =", req)
  print("opt =", opt)
  return list(req) + list(opt.values())
catch_all(1, 2, 3, a = 4, b = 5)

catch_all('a', keyword = 2)

inputs = (1, 2, 3)
keywords = {'pi' : 3.14}
catch_all(*inputs, **keywords)
```

**Variable scoping.** Like most other languages, there is a notion of the *scope* of a variable, which refers to what parts of the program is a variable name visible.

```{python}
def foo(y):
  print(y + z_outside) # 'z' must refer to a lgobal variable
  
z_outside = 2
foo(-3)

def bar(x): #Hides any global 'x'
  x = x**3
  print(x)
  
x = 5
bar(2)
print(x)

def baz(x): #Hides any gobal 'x'
  global x_global
  x_global = x**3
  print(x)
  
x_global = 5
baz(2)
print(x_global)
```

**Modifying arguments.** If an arguments is a mutable type, the function can change it!

```{python}
s0 = 3**40
s1 = s0
s0 /= 3**40
print(s0, s1)
```

```{python}
def add_nothing(s):
  assert isinstance(s, int) #recall: 'int' is immutable
  s+= 3
  print('add_nothing:', s)
  
s0 = 5
add_nothing(s0)
print(s0)
```

```{python}
def add_abcs(s):
  assert isinstance(s, list) #Recall: 'list' is mutable
  s+= ['a', 'b', 'c']
  print('add_abs:', s)
  
s1 = [1, 2, 3]
add_abcs(s1)
print(s1)
```

**Nesting functions.** You can also enclose a function definition within a function.

```{python}
def sort_dict_by_key(d, k):
  def get_key(x):
    return x
```

## **Conditionals**

Your basic *if-then-else* statement :D

```{python}
x = -15 #Try 'float('nan')`, `float('inf')`

if x == 0:
  print(x, "is zero")
elif x > 0:
  print(x, "is positive")
elif x < 0:
  print(x, "is negative")
else:
  print(x, "is unlike anything I've ever seen...")
```

For short conditionals, there is also an "inline" version (if-else only, though these can be nested):

```{python}
a, b = 5, 10
msg = 'lt' if a < b else 'geq'
print(msg)
```

```{python}
a, b = 10, 10
msg = 'lt' if a < b else ('gt' if a > b else 'eq')
print(msg)
```

## Loops

There are two main type of loops: *for* loops and *while* loops.

**for loops.**

```{python}
for N in [2, 3, 5, 7]:
  print(N, end=' ') #print all on same line
```

**Other common iterations.** The sub-expression to the right of the *in,* above, should be an *iterator,* which is a special type of object that produces a sequence of values. Indeed, what you see above is actually a shortcut for the following:

```{python}
I = iter([2, 3, 5, 7])
print(I, "\n") # "\n" is a newline character or a control character

for N in I:
  print(N, end=' ') #print all on same line
```

```{python}
print(range(10), "\n")

for i in range(10):
  print(i, end=' ') # end=' ' ends the output with a space
```

**Aside:** An iterator can be converted into an argument tuple using the \*i syntax you saw above under the section on functions.

```{python}
print(*range(5)) #same as print(0, 1, 2, 3, 4)
```

**enumerate(x):** an iterator that produces the elements of x along with a "running count" that starts at 0.

```{python}
print(*enumerate('alsdfkj'))
```

```{python}
for i, s, in enumerate('alsdfjk'):
  print(f'{i}: {s}')
```

**zip:** an iterator that produces tuples of elements taken from its input iterators.

```{python}
for a, b in zip(range(3), ['a', 'b', 'c']):
  print(a, "=>", b)
```

| This example suggests that a possible implementation of *enumerate(x)* is
| def enumerate(x):
|       return zip(range(len(x)), x)

**map:** an iterator that first applies a given function to each value.

```{python}
#find the first 10 square numbers
square = lambda x: x ** 2 # x^2
for val in map(square, range(10)):
  print(val, end=' ')
```

**filter:** an iterator that only yields values for which a given predicate function evaluates to *True*.

```{python}
#find values up to 10 for which x % 2 is zero
is_even = lambda x: x % 2 == 0
print(is_even(4), is_even(7), "\n")

for val in filter(is_even, range(10)):
  print(val, end=' ')
```

**itertools and generators.** Here is one example from *itertools:* producing combinations of a set.

```{python}
zoo = ['cat', 'dog', 'emu', 'zebra']  #a set of animals
#doesn't matter if use [] or {}

from itertools import permutations #combinations  #Also try: permutations
#for x in combinations(zoo, 3):
for x in permutations(zoo, 3):
  print(x)
```

**Set iterators.**

```{python}
for s in {1, 2, 3}:
  print(s, end=' ')
```

**Iterating over dictionaries.** By default, using a dictionary as the iterator will yield keys. To get values or key-value pairs, use .*values()* and *.items(),* respectively.

```{python}
D = {k: v for v, k in enumerate('abcdef')} #running count
print(D)
```

```{python}
for k in D: # or, for k in D.keys():
#for k in D.keys():  
  print(k, end=' ')
```

```{python}
for v in D.values():
  print(v, end=' ')
```

```{python}
print("==> Version 1:")
for p in D.items(): # (key, value) pairs
  print(p, end=' ')
  
print("\n==> Version 2:")
for k, v in D.items(): # Unpack the pairs into 'k' and 'v' variables
  print(f'{k}:{v}', end=' ')
```

**while loops.**

```{python}
i = 0
while i < 10:
  print(i, end=' ')
  i += 1 ##same as i = i +1 ##
```

**break and continue.**

```{python}
# print odd integers in [0, 20)
for n in range(20):
  if n % 2 == 0:
    continue
  print(n, end=' ')
```

```{python}
# print Fibonacci sequence for values <= 100
a, b, = 0, 1
amax = 100
L = []

while True:
  (a, b) = (b, a + b)
  if a > amax:
    break
  L.append(a) # .append() adds to the end 
  
print(L)
```
